import { chromium } from '@playwright/test';
const url = process.env.GRAFANA_URL ?? 'http://grafana:3000';
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1500, height: 700 }, deviceScaleFactor: 2 });
await p.goto(`${url}/login`);
await p.fill('input[name="user"]', 'admin');
await p.fill('input[name="password"]', 'admin');
await p.click('button[type="submit"]');
await p.waitForTimeout(3000);
await p.goto(`${url}/d/slurm-node-colour/x?viewPanel=2&kiosk`, { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
await p.screenshot({ path: '/work/.superpowers/review/states.png' });
console.log('capturé');
